---
- name: check out git repository
  become: true
  become_user: "{{ taiga_user }}"
  git:
    repo: "{{ taiga_events_repo }}"
    dest: "{{ taiga_events_checkout_dir }}"
    version: "{{ taiga_events_version }}"
  tags:
    - install
    - events-install

- name: deploy configuration file
  become: true
  become_user: "{{ taiga_user }}"
  template:
    src: config.json.j2
    dest: "{{ taiga_events_checkout_dir }}/config.json"
  tags:
    - config
    - events-config

- name: install global NPM modules
  become: true
  become_user: root
  npm:
    name: "{{ item }}"
    global: true
  with_items:
    - coffee-script
  tags:
    - install
    - events-install

- name: install local NPM modules
  become: true
  become_user: "{{ taiga_user }}"
  npm:
    path: "{{ taiga_events_checkout_dir }}"
  tags:
    - install
    - events-install

- include: "{{ taiga_service_manager }}.yml"
