---
sudo: true
dist: trusty

language: python
python:
  - "2.7"
  - "3.5"

addons:
  apt:
    packages:
      - python-pip

# Doc: https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix
env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.4.0.0

branches:
  only:
    - master

install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/syntax-check/inventory taiga.yml --syntax-check
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then ansible-lint taiga.yml; fi
