---
- name: deploy SSL private key
  become: true
  become_user: taiga
  copy:
    dest: "{{ _taiga_ssl_key_path }}"
    mode: "0640"
    content: "{{ taiga_ssl_key }}"
  tags:
    - config
    - front-config
    - offline

- name: deploy SSL certificate
  become: true
  become_user: taiga
  copy:
    dest: "{{ _taiga_ssl_certificate_path }}"
    mode: "0644"
    content: "{{ taiga_ssl_certificate }}"
  tags:
    - config
    - front-config
    - offline
