---
- name: restart circus
  become: true
  become_user: root
  service:
    name: circusd
    state: restarted

- name: restart systemd
  become: true
  become_user: root
  command: systemctl daemon-reload
