---
- name: restart circus
  become: true
  become_user: root
  service:
    name: circusd
    state: restarted

- name: reload systemd daemon
  become: true
  become_user: root
  systemd:
    daemon_reload: true
