---
- name: check for required variables
  assert:
    that:
      - "taiga_secret_key is defined"
      - "taiga_rabbitmq_password is defined or not (taiga_enable_events | bool or taiga_enable_async_tasks | bool)"
      - "taiga_service_manager == 'circus' or ansible_version | version_compare('2.2', '>=')"
  with_items:
    - taiga_secret_key

- name: set facts identifying node roles
  set_fact:
    _taiga_is_back_node: "{{ 'taiga-back' in group_names }}"
    _taiga_is_front_node: "{{ 'taiga-front' in group_names }}"
    _taiga_is_events_node: "{{ 'taiga-events' in group_names }}"
  tags:
    always

- name: populate hosts file
  become: true
  become_user: root
  lineinfile:
    dest: /etc/hosts
    regexp: '{{ hostvars[item].ansible_default_ipv4.address }}.*{{ item }}$'
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].ansible_fqdn }} {{ item }}"
    state: present
  with_items: "{{ groups.all }}"
  when: >
    taiga_populate_hosts
    and (hostvars[item].ansible_default_ipv4 is defined)
  tags:
    - config
    - front-config
    - back-config
    - events-config

- name: "create user {{ taiga_user }}"
  become: true
  become_user: root
  user:
    name: "{{ taiga_user }}"
    groups: sudo
    home: "{{ taiga_user_home }}"
  tags:
    - install
    - front-install
    - back-install
    - events-install

- name: "create logs directory"
  become: true
  become_user: root
  file:
    path: "{{ taiga_log_dir }}"
    state: directory
    owner: "{{ taiga_user }}"
    group: "{{ taiga_user }}"
  tags:
    - install
    - front-install
    - back-install
    - events-install

- name: update package cache
  become: true
  become_user: root
  apt:
    update_cache: true
  tags:
    - install
    - front-install
    - back-install
    - events-install

- name: fail on unsupported service manager
  fail:
    msg: "Unsupported value for taiga_service_manager, must be 'circus' or 'systemd'"
  when: taiga_service_manager not in ['circus', 'systemd']
  tags:
    - always

- include: "{{ taiga_service_manager }}.yml"
