- name: optionally install packages for LDAP authentication into virtualenv
  become: true
  become_user: "{{ taiga_user }}"
  pip:
    name: taiga-contrib-ldap-auth
    virtualenv: "{{ taiga_user_home }}/{{ taiga_back_venv_dir }}"
    virtualenv_python: "python3"
    state: "{{ taiga_upgrade | bool | ternary('latest', 'present') }}"
  notify:
    - "restart taiga (via {{ taiga_service_manager }})"
  tags:
    - install
    - back-install
