- name: install Redis
  become: true
  become_user: root
  apt:
    name: redis-server
    state: "{{ taiga_upgrade | bool | ternary('latest', 'present') }}"
  tags:
    - install
    - back-install

