---
# What repo should we check out?
taiga_front_repo: "{{ taiga_git_mirror }}/taiga-front-dist.git"
taiga_front_checkout_dir: "{{ taiga_user_home }}/taiga-front-dist"
taiga_front_version: "{{ taiga_version }}"

# Where should we write our logs?
taiga_front_log_dir: "{{ taiga_log_dir }}"

# Do we want to enable debugging for the frontend?
taiga_front_debug: "{{ taiga_debug }}"

# Do we want to expose the Django admin interface in the front end?
taiga_front_enable_django_admin: false
