---
- name: set fact to determine front end install mode
  set_fact:
    _taiga_front_install_mode: "{{ 'dist' if '-dist' in taiga_front_repo else 'gulp' }}"
  tags:
    always

- name: check out git repository
  become: true
  become_user: "{{ taiga_user }}"
  git:
    repo: "{{ taiga_front_repo }}"
    dest: "{{ taiga_front_checkout_dir }}"
    version: "{{ taiga_front_version }}"
  notify:
    - restart nginx
  tags:
    - install
    - front-install

- include: "{{ _taiga_front_install_mode }}.yml"

- name: deploy configuration file
  become: true
  become_user: "{{ taiga_user }}"
  template:
    mode: '0644'
    src: conf.json.j2
    dest: "{{ taiga_front_checkout_dir }}/dist/conf.json"
  notify:
    - "restart {{ taiga_service_manager }}"
  tags:
    - config
    - front-config
