---
- name: check out git repository
  become: true
  become_user: "{{ taiga_user }}"
  git:
    repo: "{{ taiga_front_repo }}"
    dest: "{{ taiga_front_checkout_dir }}"
    version: "{{ taiga_front_version }}"
  notify:
    - restart nginx
  tags:
    - install
    - front-install

- name: deploy configuration file
  become: true
  become_user: "{{ taiga_user }}"
  template:
    mode: '0644'
    src: conf.json.j2
    dest: "{{ taiga_front_checkout_dir }}/dist/conf.json"
  notify:
    - "restart {{ taiga_service_manager }}"
  tags:
    - config
    - front-config
