---
- name: install frontend-specific packages
  become: true
  become_user: root
  apt:
    name: "{{ item }}"
  with_items:
    - nginx
  tags:
    - install
    - front-install

- name: check out git repository
  become: true
  become_user: "{{ taiga_user }}"
  git:
    repo: "{{ taiga_front_repo }}"
    dest: "{{ taiga_front_checkout_dir }}"
    version: "{{ taiga_front_version }}"
  tags:
    - install
    - front-install

- name: "make nginx configuration directory writeable for user {{ taiga_user }}"
  become: true
  become_user: root
  file:
    path: /etc/nginx/conf.d
    owner: root
    group: taiga
    mode: '0775'
  tags:
    - config
    - front-config

- name: "remove nginx default site"
  become: true
  become_user: root
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - restart nginx
  tags:
    - config
    - front-config

- name: add taiga to nginx
  become: true
  become_user: "{{ taiga_user }}"
  template:
    src: taiga.conf.j2
    dest: "/etc/nginx/conf.d/taiga.conf"
  notify:
    - restart nginx
  tags:
    - config
    - back-config

- name: deploy configuration file
  become: true
  become_user: "{{ taiga_user }}"
  template:
    mode: '0644'
    src: conf.json.j2
    dest: "{{ taiga_front_checkout_dir }}/dist/conf.json"
  notify:
    - restart nginx
  tags:
    - config
    - front-config

- name: enable nginx service
  become: true
  become_user: root
  service:
    name: nginx
    state: started
  tags:
    - config
    - front-config
